### ISSUE TITLE
MYSQL Destroy dont delete row in mysql

### ISSUE THREAD

**Issue by krubenrc** [phalcon/incubator#857] opened 2018-04-16 18:46 UTC
Hello, im using the session adapter to mysql and i found that when is called the function destroy, it dont delete the row in the table of mysql.

I tried to delete table with execute(delete from table ...) and neither work.
Also i tried changing name of the table to other table, in the query execution, and it worked. 
```
$result = $this->connection->execute("delete from othertable");
```

You can help me please? :)

**Comment by krubenrc** [comment] 2018-04-17 18:40
Hi!
I've been investigating about this.
The delete query is working fine, but right after that, the write function of the adapter is called and the session is reinserted into the database.

**Comment by krubenrc** [comment] 2018-04-17 18:48
I added  **session_write_close();**  at the beginning of the destroy function.

Now it looks like this:

`    public function destroy($session_id = null)
    {
        session_write_close();
        if (!$this->isStarted()) {
            return true;
        }

        if (is_null($session_id)) {
            $session_id = $this->getId();
        }

        $this->_started = false;
        $options = $this->getOptions();
        $result = $this->connection->execute(
            sprintf(
                'DELETE FROM %s WHERE %s = ?',
                $this->connection->escapeIdentifier($options['table']),
                $this->connection->escapeIdentifier($options['column_session_id'])
            ),
            [$session_id]
        );

        return $result;
    }`

When you can, tell me if is a good form to resolve this error.
Thanks in advance.

**Comment by sergeysviridenko** [comment] 2018-04-25 08:02
Which versions of phalcon and incubator do you use?

**Comment by sergeyklay** [comment] 2018-06-07 09:45
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises

**Closed by sergeyklay** 2018-06-07 09:45 UTC
Labels: MySQL, Need information

**Comment by mostvotedplaya** [comment] 2018-07-31 04:07
The issue is the write method.

If your going to logout of a site you would use something such as:

```
$this->session->destroy();
```

Which will invoke the destroy method in the session class, but directly after write is called so the data first gets deleted but then the write method just re-inserts it.

You should follow what i did below to fix it:

```
protected $destroyed;

public function write($sid, $data)
{
    if ($this->destroyed === true) {
        return true;
    }

    // ...
}

public function destroy($sid)
{
    $this->destroyed = true;

    //  ...
}
```
