### ISSUE TITLE
DI is not found in MongoCollection using Phalcon 3.1 and PHP 7.1

### ISSUE THREAD

**Issue by MaksSlesarenko** [phalcon/incubator#760] opened 2017-04-14 10:31 UTC
Getting error in MongoCollection after updating to Phalcon 3.1.2 and PHP 7.1

```php
$file = File::findFirst()
$file->name = 'test';
$file->save();


A dependency injector container is required to obtain the services related to the ODM
                                                                                         
  [Phalcon\Mvc\Collection\Exception]                                                     
  A dependency injector container is required to obtain the services related to the ODM  
                                                                                         

Exception trace:
 () at ...vendor/phalcon/incubator/Library/Phalcon/Mvc/MongoCollection.php:76
 Phalcon\Mvc\MongoCollection->save()
```

Current workaround in model class
```php
 public function save()
    {
        if (version_compare(PHP_VERSION, '7.1.0') >= 0) {
            $this->_dependencyInjector = \Phalcon\Di::getDefault();
            $this->_modelsManager = $this->_dependencyInjector->getShared("collectionManager");
            $this->_modelsManager->initialize($this);
        }

        return parent::save();
    }
```
### Details

* Phalcon Framework version: 3.1.2
* Phalcon Incubator version: 3.0 & 3.1
* PHP Version: 7.1.2
* Operating System: Centos
* Server: CLI
* Other related info (Database, table schema): Mongo

**Comment by tkroll** [comment] 2017-04-18 13:37
Related: https://forum.phalconphp.com/discussion/15927/mongocollection-wont-save

Also seems to be ignoring getReservedAttributes()

**Comment by MaksSlesarenko** [comment] 2017-05-10 09:53
I've updated issue, error happens on update not insert

**Comment by Jurigag** [comment] 2017-05-10 10:04
MongoCollection extends `Phalcon\Mvc\Collection`. Here is collection construction - https://github.com/phalcon/incubator/blob/master/Library/Phalcon/Mvc/MongoCollection.php#L186, here it sets dependencyInjector - 
https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/collection.zep#L95 

Not sure what happens, it should work. Any idea?

**Comment by MaksSlesarenko** [comment] 2017-05-10 10:14
@Jurigag  look at @tkroll  comment

**Comment by Jurigag** [comment] 2017-05-10 10:42
For me on php 7.0.13 it works but i have:

```
Uncaught MongoDB\Driver\Exception\BulkWriteException: Mod on _id not allowed
```

From code like:

```
$robots = new Robots();
$robots->name = 'test';
$robots->create();
$robots = Robots::findFirst();
var_dump($robots->toArray());
$robots->name = 'test2';
$robots->save();
```

I guess when updating collection we should remove `_id`

**Comment by micheleangioni** [comment] 2017-05-11 14:29
@sergeyklay I'm having the same problem. Updating to PHP 7.1 and Phalcon 3.1.2 somehow broke an application where we are using Mongo.

I get `A dependency injector container is required to obtain the services related to the ODM` when updating records.

Instead, when deleting records I get

```php
Error: Call to a member function notifyEvent() on array

/var/www/wiki/vendor/phalcon/incubator/Library/Phalcon/Mvc/MongoCollection.php:467
/var/www/wiki/vendor/phalcon/incubator/Library/Phalcon/Mvc/MongoCollection.php:352
```

I do not know whether @sergeyklay is the maintainer or someone else, but please this should have very high priority since Mongo currently is not usable.

Thanks!

**Comment by Jurigag** [comment] 2017-05-11 14:43
I can't reproduce it, i checked it on latest phalcon and incubator and it works fine, i have other error above.

**Comment by micheleangioni** [comment] 2017-05-11 14:48
It's strange you cannot reproduce it, since many people are having the same problem..

Are you using PHP 7.1? Because with PHP 7.0 it probably works fine

**Comment by Jurigag** [comment] 2017-05-11 14:51
Yes, using php 7.1 i have:

```
Uncaught MongoDB\Driver\Exception\BulkWriteException: Mod on _id not allowed
```

**Comment by micheleangioni** [comment] 2017-05-11 15:18
Interesting question, though in the app I use the FactoryDefault, in the tests it's the `Phalcon\Test\UnitTestCase` class that sets the DI with `$di = new Di();` where DI is `use Phalcon\Di;`, after a `Di::reset();`,  [line 63](https://github.com/phalcon/incubator/blob/master/Library/Phalcon/Test/UnitTestCase.php#L63)

**Comment by Jurigag** [comment] 2017-05-11 15:28
Then idk, i just don't have it really. Weird issue, and this problem you have in both, like app and tests?

**Comment by micheleangioni** [comment] 2017-05-11 16:01
It seems both, but tomorrow I'll make some more detailed checks!

**Comment by Jurigag** [comment] 2017-05-11 16:12
I just don't have this error, which is weird, you could try doin something like Di::setDefault($di) but i doubt it will fix it. dependencyInjector is set in parent class. Further it's not lost anywhere as you trying to talk. Though surely there is problem with those reserved attributes, maybe it's causing this di error, not sure.

**Comment by micheleangioni** [comment] 2017-05-12 08:01
@Jurigag ok, it seems the errors are present **only in tests**.
So the problem seems to be something related with the Incubator itself, between the Mongo and Test modules?

In the parent class I have `$di = Di::getDefault();`. Even if I change it to `$di = new \Phalcon\DI\FactoryDefault();` and/or add ` Di::setDefault($di);` nothing changes.

I agree that's weird.. but several people seem to have the same problem. 
In the parent class I have

```php
// [...]
use Phalcon\Db\Adapter\MongoDB\Client;
use Phalcon\Test\UnitTestCase as PhalconTestCase;

abstract class WebTestCase extends PhalconTestCase
{

// [...]

 public function setUp()
    {
        parent::setUp();

        // Load any additional services that might be required during testing
        $di = Di::getDefault();

        // [...]

        /**
         * Database connection is created based in the parameters defined in the configuration file
         */
        $di->setShared('mongo', function () {
            $dsn = 'mongodb://' . env('DB_HOST', 'localhost');

            $mongo = new Client($dsn);

            return $mongo->selectDatabase(env('DB_NAME'));
        });

        // Collection Manager is required for MongoDB
        $di->setShared('collectionManager', function () {
            return new Manager();
        });

        // [...]
    }

// [...]

}
```

But before upgrading to PHP 7.1 and Phalcon 3.1.2 it was working without problems.
If something comes to your mind that I could do to help you reproduce the error, please let me know. Unfortunately I cannot open source the code.

**Comment by micheleangioni** [comment] 2017-05-15 13:47
I can confirm I have this problem also in the web (i.e. not in tests).

Here is the error when I try to save a model:

```
A dependency injector container is required to obtain the services related to the ODM`

#0 /var/www/[...]: Phalcon\Mvc\MongoCollection->save()
#1 /var/www/[...]: [...]->[...]()
#2 [internal function]: [...]->requested(Object(Phalcon\Events\Event), Object([...]), Object([...]))
#3 [internal function]: Phalcon\Events\Manager->fireQueue(Array, Object(Phalcon\Events\Event))
#4 /var/www/[...](143): Phalcon\Events\Manager->fire('[...]', Object([...]), Object([...]))
#5 [internal function]: [...]
#6 [internal function]: Phalcon\Dispatcher->callActionMethod(Object([...]), '[...]', Array)
#7 [internal function]: Phalcon\Dispatcher->_dispatch()
#8 [internal function]: Phalcon\Dispatcher->dispatch()
#9 /var/www/[...]/public/index.php(35): Phalcon\Mvc\Application->handle()
#10 {main}
```

Is there any progress about this?

**Comment by Jurigag** [comment] 2017-05-15 15:29
If someone will post full script to reproduce then sure i guess.

**Comment by tkroll** [comment] 2017-05-16 15:40
Can someone test 7.1.5.
RE: Fixed bug #74188 (Null coalescing operator fails for undeclared static class properties).

This is interesting as many static props were undeclared.

**Comment by micheleangioni** [comment] 2017-05-16 15:52
@tkroll still same problem with

`PHP 7.1.5-1+deb.sury.org~xenial+1`

**Comment by tkroll** [comment] 2017-05-16 15:54
Boo. Thanks for trying. It was a shot in the dark.

**Comment by Jurigag** [comment] 2017-05-16 16:17
It works for me on 7.1.0, i just have error what i wrote above, someone needs to create repo with full code to reproduce.

**Comment by Jurigag** [comment] 2017-05-17 11:35
https://github.com/phalcon/incubator/pull/768

As you see we don't have error with this Di thing, we need script to reproduce.

**Comment by Jurigag** [comment] 2017-05-23 14:41
@baychae why you thumb down? If you have script to reproduce then post it please.

**Comment by micheleangioni** [comment] 2017-05-23 15:45
@Jurigag @sergeyklay  I have now a public repo that shows this problem.

[PHP 7.0](https://travis-ci.org/micheleangioni/phalcon-repositories/jobs/235275595) : just 1 test failing
[PHP 7.1](https://travis-ci.org/micheleangioni/phalcon-repositories/jobs/235275596) : ALL Mongo tests failing

[PHP 7.1 with FIX](https://travis-ci.org/micheleangioni/phalcon-repositories/jobs/235260523) : just 1 test failing

Conclusions:

1. Without the fix, in PHP 7.1 all tests fail, in PHP 7.0 only one
2. Locally no tests are failing in PHP 7.0 and in PHP 7.1 with FIX, could you take a look and try to understand why that test is failing on Travis? Thanks

Imho the bug level is Medium or High.

**Comment by Jurigag** [comment] 2017-05-23 16:07
@micheleangioni i have this thing about _id too, i think it's about mongodb/mongodb extension version, that from some version they disabled option to update `_id` field.

**Comment by micheleangioni** [comment] 2017-05-23 16:11
@Jurigag it might be, but in the failing test I am NOT updating the _id field, that's the point! 
I am updating another field. 

We have to understand how to fix both problems, because at the moment this Mongo library is not usable :(

**Comment by Jurigag** [comment] 2017-05-23 16:12
@micheleangioni yea yea, you are not updating _id field, but phalcon just pass to mongodb update method _id in array - this is why there is this error.

**Comment by baychae** [comment] 2017-05-23 16:53
@Jurigag If this is an easy fix could you provide it here? This is a blocking issue for me.

**Comment by Jurigag** [comment] 2017-05-23 17:04
https://github.com/phalcon/incubator/blob/master/Library/Phalcon/Mvc/MongoCollection.php#L125

Here most be removed `_id` from toArray() result.

**Comment by baychae** [comment] 2017-05-23 17:10
My problem must be something else.

My error occurs here:

https://github.com/phalcon/incubator/blob/master/Library/Phalcon/Mvc/MongoCollection.php#L75 <https://github.com/phalcon/incubator/blob/master/Library/Phalcon/Mvc/MongoCollection.php#L75>

Error message is here (same as OP):

https://github.com/phalcon/incubator/blob/master/Library/Phalcon/Mvc/MongoCollection.php#L77 <https://github.com/phalcon/incubator/blob/master/Library/Phalcon/Mvc/MongoCollection.php#L77>

**Comment by Jurigag** [comment] 2017-05-23 17:11
@baychae yea but we need script to reproduce your problem and OP problem, right now i can't so can't fix it.

**Comment by Jurigag** [comment] 2017-05-24 08:21
Any idea why when testing locally i have:

```
1) CollectionsTest: Collections save
 Test  tests/unit5x/Mvc/MongoCollectionTest.php:testCollectionsSave

  [Error] Call to a member function notifyEvent() on array

/root/incubator/Library/Phalcon/Mvc/MongoCollection.php:348
/root/incubator/tests/unit5x/Mvc/MongoCollectionTest.php:382
/root/incubator/tests/unit5x/Mvc/MongoCollectionTest.php:84
/root/incubator/vendor/phpunit/phpunit/src/Framework/TestCase.php:908
/root/incubator/vendor/phpunit/phpunit/src/Framework/TestCase.php:768
/root/incubator/vendor/phpunit/phpunit/src/Framework/TestResult.php:612
/root/incubator/vendor/phpunit/phpunit/src/Framework/TestCase.php:724
/root/incubator/vendor/phpunit/phpunit/src/Framework/TestSuite.php:722
/root/incubator/vendor/codeception/codeception/src/Codeception/PHPUnit/Runner.php:106
/root/incubator/vendor/codeception/codeception/src/Codeception/SuiteManager.php:157
/root/incubator/vendor/codeception/codeception/src/Codeception/Codecept.php:184
/root/incubator/vendor/codeception/codeception/src/Codeception/Codecept.php:153
/root/incubator/vendor/codeception/codeception/src/Codeception/Command/Run.php:288
/root/incubator/vendor/symfony/console/Command/Command.php:264
/root/incubator/vendor/symfony/console/Application.php:835
/root/incubator/vendor/symfony/console/Application.php:200
/root/incubator/vendor/symfony/console/Application.php:124
/root/incubator/vendor/codeception/codeception/src/Codeception/Application.php:103
/root/incubator/vendor/codeception/codeception/codecept:36
```

Though in travis it's fine?

**Comment by micheleangioni** [comment] 2017-05-24 09:00
@Jurigag nice to hear to know how to fix the _id issue. Please try to push the fix asap, it's really a blocking problem! Thanks :)

About the `[Error] Call to a member function notifyEvent() on array` error, that's the other bug, the PHP 7.1 one.

The Travis build without the FIX is failing as well, take a look [here](https://travis-ci.org/micheleangioni/phalcon-repositories/jobs/235275596) . Maybe for some reason you are not having the problem locally, but I do have it both locally and on Travis.

The branch with the FIX [has NOT with problem](https://travis-ci.org/micheleangioni/phalcon-repositories/jobs/235260523).

The FIX I'm speaking about is just adding [this trait](https://github.com/micheleangioni/phalcon-repositories/blob/master/src/PhalconRepositories/MongoFix.php) to the Model [in the tests](https://github.com/micheleangioni/phalcon-repositories/blob/master/tests/CollectionRepositoryTest.php#L317).

As a summary: we have **TWO** bugs:

1. The _id bug, that is a blocking problem and needs ASAP fix
2. The `[Error] Call to a member function notifyEvent() on array` bug, that can be fixed with that workaround but needs a fix anyway inside Incubator.

Hope to have been as clear as possible!

**Comment by Jurigag** [comment] 2017-05-24 10:47
This is not a fix, this is workaround, issue is happening because getReservedAttributes is not working.

**Comment by micheleangioni** [comment] 2017-05-24 11:11
Absolutely agree this is only a workaround, as I wrote!

However in Travis PHP 7.0 seems to be ok. Maybe it has been fixed in a recent version of PHP 7.0 or viceversa it has recently happened in 7.0 too. 
Who is the responsible for zephire, sergeyklay?

**Comment by Jurigag** [comment] 2017-05-24 11:14
We are responsible for zephir obviously, it's part of phalcon.

**Comment by micheleangioni** [comment] 2017-05-24 11:28
Yeah yeah I know, I mean the main person. 
However, should we open an issue on the zephir repo? Is someone already investigating the zephir bug? Just to know if there is a plan, not to make pressure :)

**Comment by Jurigag** [comment] 2017-05-24 11:38
I already opened it and added test.

**Comment by micheleangioni** [comment] 2017-05-24 13:23
Great :)

**Comment by Jurigag** [comment] 2017-05-24 14:34
Actually it's not zephir issue, it's php bug - https://bugs.php.net/bug.php?id=74648

https://github.com/phalcon/cphalcon/pull/12862 here will be fix for this DI/modelsManager etc issue.

**Comment by micheleangioni** [comment] 2017-06-07 09:40
Hi @Jurigag , 
I see you are fixing the `notifyEvent()` bug/problem in [phalcon/cphalcon/pull/12862](https://github.com/phalcon/cphalcon/pull/12862), looking forward for the fix to be complete :)

About the `_id` problem, is there a PR o fix in progress? 
Thanks!

**Comment by aliel** [comment] 2017-06-10 02:04
> About the _id problem, is there a PR o fix in progress?
Thanks!

+1

**Comment by Jurigag** [comment] 2017-06-12 12:01
https://github.com/phalcon/cphalcon/pull/12891 waiting for merging this, then i will change build script because currently incubator uses latest stable phalcon(we need to use source and zephir) and will fix this _id issue and check if tests are passing.

**Comment by Jurigag** [comment] 2017-06-20 09:08
Okay i merged mod on `_id` fix. Though we don't have update method at all in `Phalcon\Mvc\MongoColection` which seems weird. All should work now. If someone who is using mongo in their app could check Latest phalcon(3.2) and incubator on 3.2.x branch to check if everything works it could be good. Then i will merge this `mod on _id` fix to master if everything is fine, if not will try to fix other stuff and then new release.

**Comment by tkroll** [comment] 2017-06-20 10:36
Just did:
git clone https://github.com/phalcon/cphalcon
cd cphalcon/build
sudo ./install --phpize /usr/bin/phpize7.1 --php-config /usr/bin/php-config7.1

then

composer require phalcon/incubator:^3.2

Got this error:

PHP Fatal error:  Uncaught Phalcon\Mvc\Collection\Exception: A dependency injector container is required to obtain the services related to the ODM in /var/www/outsmart/shared/utils/incubator/Library/Phalcon/Mvc/MongoCollection.php:77

**Comment by Jurigag** [comment] 2017-06-20 10:39
Script to reproduce?

**Comment by tkroll** [comment] 2017-06-20 10:44
$u = User::findByEmail('test@test.com');
$u->helloThere = 1;
echo $u->email, PHP_EOL;
$u->save();

My User class extends \Phalcon\Mvc\MongoCollection. It echos correctly.

**Comment by Jurigag** [comment] 2017-06-20 11:13
Hmmmmm. Could you try other database? It's possible that you just have in mongo `_dependencyInjector` key saved.

**Comment by tkroll** [comment] 2017-06-20 11:27
Oh snap! Good call.

Did a quick:

`
db.user.update(
	{}, 
	{
		$unset: {
			"_dependencyInjector":1,
			"_modelsManager":1,
			"_source":1,
			"_operationMade":1,
			"_dirtyState":1,
			"_connection":1,
			"_errorMessages":1,
			"_skipped":1
		}
	},
	{multi:1}
)
`
And we appear to be back in business!

**Comment by Jurigag** [comment] 2017-06-20 11:28
Yea now the question is:

- should people just update their databases to unset those keys
- or we should unset them in framework?

**Comment by tkroll** [comment] 2017-06-20 11:41
I'd think outside the framework. It's a bit of work to do every time.

This worked for me. No warranty on this.

https://gist.github.com/tkroll/53fa3e9151d9232e7399e313b503dc97

**Comment by Jurigag** [comment] 2017-06-20 11:44
Okay, so now i will close it, let me know if anything other occur, also there is this - https://github.com/phalcon/incubator/issues/794 if you could comment here it could be good.

**Closed by Jurigag** 2017-06-20 11:44 UTC
Labels: Bug - Medium, Mongo

**Comment by micheleangioni** [comment] 2017-07-04 15:57
@Jurigag I'm still having problems.
Please take a look at [this Travis build](https://travis-ci.org/micheleangioni/phalcon-repositories/jobs/235260523)

I am using the last Incubator version

Line 1070: `  - Installing phalcon/incubator (dev-master 4913dc0): Cloning 4913dc021f`

Any clue? Thanks

**Comment by Jurigag** [comment] 2017-07-04 20:25
It's fixed line above with `unset($data['_id']);`

**Comment by micheleangioni** [comment] 2017-07-07 07:57
@Jurigag ok now I get it, the PR has been merged in the 3.2.x branch but NOT in the Master branch. Is that really ok? Shouldn't be merged in both?

**Comment by Jurigag** [comment] 2017-07-07 08:29
It wasn't? Oh i must forgot it. Let me merge it.

**Comment by micheleangioni** [comment] 2017-07-07 08:57
Thanks :)

**Comment by Jurigag** [comment] 2017-07-07 10:02
Great, happy to hear, also i would like to know your opinion about https://github.com/phalcon/incubator/issues/794
