### ISSUE TITLE
MongoCollection find: PHP Fatal Error MongoDB\BSON\Serializable not found

### ISSUE THREAD

**Issue by ktrhn** [phalcon/incubator#782] opened 2017-05-25 19:12 UTC
Strange issue when doing `find` on `MongoCollection`

Some requests work without an issue, same request later I get the following fatal error, seems totally random. Got this on multiple machines (OS X and Gentoo Linux). PHP 7.1.1 and 7.1.5, Phalcon 3.1.2, current phalcon-incubator, php-mongodb-driver 1.2.9, mongodb 3.4.4. I also tried downgrading php-mongodb-driver and phalcon-incubator. Did not change anything.

> 2017/05/25 19:40:51 [error] 1592#1592: *107 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Interface 'MongoDB\BSON\Serializable' not found in […]/vendor/phalcon/incubator/Library/Phalcon/Db/Adapter/MongoDB/Model/BSONArray.php on line 17" while reading response header from upstream, client: ::ffff:178.24.75.225, server: […], request: "GET […] HTTP/2.0", upstream: "fastcgi://unix:/run/php-fpm/php7.1.sock:", host: "[…]", referrer: "[…]"

More strangely setting `mongodb.debug="1"` in `php.ini` functions as a workaround, the error does not seem to occur with this setting.

**Comment by scottf-tvw** [comment] 2017-05-27 18:11
I am now getting the same error. but for Unserializable. it was working fine in a composer pull from a few weeks ago.

**Comment by ktrhn** [comment] 2017-05-29 00:42
Sometimes the php handler just dies and does not even output the error. So mybe this is some problem in the underlying php-mongodb-driver?

```
# php7.1 cli/app.php Mongo prices     
[1]    10806 segmentation fault  php7.1 cli/app.php Mongo prices

**Comment by Jurigag** [comment] 2017-05-29 07:56
Since it's seg fault, post please stack from gdb.

**Comment by ktrhn** [comment] 2017-06-13 13:57
Seems to be related to mongodb and not phalcon, although I am not sure if it is really the same error as in the first post.
https://github.com/mongodb/mongo-php-library/issues/374

**Comment by Jurigag** [comment] 2017-06-13 15:16
So you reproduced it on without phalcon? We can close it?

**Comment by ktrhn** [comment] 2017-06-13 15:19
I am not sure. I could not reproduce the original fatal error "MongoDB\BSON\Serializable not found" on cli. With fpm i am getting the sporadic php fatal error, on cli I get the sporadic segfaults. All a little strange.

**Comment by Jurigag** [comment] 2017-06-20 08:54
Hmm i will close this for now, if you think there is bug then ping me.

**Closed by Jurigag** 2017-06-20 08:54 UTC
Labels: Mongo

**Comment by tejastank** [comment] 2018-03-28 19:10
I had faced same issue,

I had fired pecl install mongodb, than
sudo service php7.0-fpm restart
sudo service apcahe2 restart

And my exact same issue shorted :)

**Comment by KyleFromOhio** [comment] 2019-11-02 19:02
I had this same issue.

**I rebooted server and error disappeared.**
Might have been caused by some php package updates or linux kernel updates. No idea.
